sudo: required
language: node_js
node_js:
  - '0.12'
before_script:
  - npm install -g bower grunt-cli
  - bower install
  - gem install sass
services: mongodb
before_install:
  - sudo chown -R $USER /usr/local
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
