language: node_js
node_js:
  - '0.10'
  - '0.12'
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb
before_install:
  - apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
sudo: false
