version: 2
jobs:
  build:
    docker:
      - image: mdphbeta/node-mdph:1.0.2
      - image: mongo:3.4.2
      - image: selenium/standalone-chrome:3.1.0
    working_directory: /home/ubuntu/mdph
    steps:
      - checkout

      - restore_cache:
          key: mdph-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          key: mdph-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "/root/.cache/yarn"

      - run:
          name: Run unit tests
          command: yarn test

      - run:
          name: Build package
          command: yarn build

      - run:
          name: Run test server
          command: yarn circle-server
          background: true

      - run:
          name: Run e2e tests
          command: yarn circle-e2e

      - add-ssh-keys:
          fingerprints:
            - "01:c8:ab:b5:3f:8f:77:f5:4f:b8:8d:ef:3f:f4:28:9a"

      - deploy:
           command: |
                      if [ "${CIRCLE_BRANCH}" == "circle_2_deploy" ]; then
                        yarn build
                        scp -oStrictHostKeyChecking=no -r ${HOME}/${CIRCLE_PROJECT_REPONAME}/dist/. ${DEPLOY_USER}@${DEPLOY_SERVER}:${DEPLOY_DIR}/.
                      fi
